parameters:
#    brs_page.example.class: BRS\PageBundle\Example

services:
#    brs_page.example:
#        class: %brs_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
