parameters:
    brs_page.listener: BRS\PageBundle\EventListener\PageListener

services:
    brs_page.onFlush:
        class: %brs_page.listener%
        tags:
          - { name: doctrine.event_listener, event: preFlush }
    brs_page.preRemove:
        class: %brs_page.listener%
        tags:
          - { name: doctrine.event_listener, event: preRemove }
#    brs_page.postUpdate:
#        class: %brs_page.listener%
#        tags:
#          - { name: doctrine.event_listener, event: postUpdate }

#        arguments: [@service_id, "plain_value", %parameter%]
